#cloud-config
package_upgrade: true
packages:
  - kali-desktop-xfce
  - xrdp
  - wireguard
  - wireguard-tools
  - openssl
write_files:
  - path: /home/${admin_username}/.xsession
    owner: ${admin_username}:${admin_username}
    permissions: '0644'
    content: |
      xfce4-session
  - path: /home/${admin_username}/.hushlogin
    owner: ${admin_username}:${admin_username}
    permissions: '0644'
runcmd:
  - DEBIAN_FRONTEND=noninteractive apt install -f gdm3
  - echo "root:root" | chpasswd
  - systemctl enable xrdp
  - systemctl start xrdp
  - cp /etc/skel/.bashrc /home/${admin_username}/.bashrc
  - chown ${admin_username}:${admin_username} /home/${admin_username}/.bashrc
  - cp /etc/skel/.zshrc /home/${admin_username}/.zshrc
  - chown ${admin_username}:${admin_username} /home/${admin_username}/.zshrc
  - mkdir -p /etc/wireguard
  - echo -e "[Interface]\nPrivateKey = ${kali_private_key}\nAddress = 10.1.10.1/24\nListenPort = 51820\n\n[Peer]\nPublicKey = ${client_public_key}\nAllowedIPs = 10.1.10.2/32" > /etc/wireguard/wg0.conf
  - chmod 600 /etc/wireguard/wg0.conf
  - chown root:root /etc/wireguard/wg0.conf
  - wg-quick up wg0
  - systemctl enable wg-quick@wg0
  - touch /home/kali/.hushlogin 
  - touch /root/.hushlogin

