#cloud-config
package_upgrade: true
packages:
  - kali-linux-everything
  - kali-desktop-xfce
  - xrdp
  - wireguard
write_files:
  - path: /home/${admin_username}/.xsession
    content: |
      xfce4-session
  - path: /etc/wireguard/wg0.conf
    owner: root:root
    permissions: '0644'
    content: |
      [Interface]
      PrivateKey = ${wg_private_key}
      Address = 10.1.10.1/24
      ListenPort = 51820

      [Peer]
      PublicKey = ${client_public_key}
      AllowedIPs = 10.1.10.2/32
runcmd:
  - systemctl enable xrdp
  - systemctl start xrdp
  - touch /home/${admin_username}/.hushlogin
  - wg-quick up wg0
  - systemctl enable wg-quick@wg0

