#cloud-config
package_upgrade: true
packages:
  - kali-desktop-xfce
  - xrdp
  - wireguard
  - wireguard-tools
  - openssl
  - gdm3
runcmd:
  - echo "xfce4-session" > /home/kali/.xsession
  - chown kali:kali /home/kali/.xsession
  - chmod 0644 /home/kali/.xsession
  - |
    cat > /etc/wireguard/wg0.conf << EOF
    [Interface]
    PrivateKey = ${kali_private_key}
    Address = 10.1.10.1/24
    ListenPort = 51820

    [Peer]
    PublicKey = ${client_public_key}
    AllowedIPs = 10.1.10.2/32
    EOF
  - chmod 0600 /etc/wireguard/wg0.conf
  - systemctl enable xrdp
  - systemctl start xrdp
  - systemctl enable wg-quick@wg0
  - wg-quick up wg0
